// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package inject

import (
	"cloud.google.com/go/pubsub"
	"context"
	"github.com/ONSdigital/ras-rm-sample/file-uploader/config"
	"github.com/ONSdigital/ras-rm-sample/file-uploader/file"
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
)

// Injectors from injector.go:

func Inject() file.FileProcessor {
	config := ConfigSetup()
	context := GenContext()
	client := NewPubSub(config, context)
	fileProcessor := NewFileProcessor(config, client, context)
	return fileProcessor
}

// injector.go:

var FileProcessor = Inject()

func ConfigSetup() config.Config {
	viper.AutomaticEnv()
	configureLogging()
	viper.SetDefault("PORT", "8080")
	viper.SetDefault("PROJECT_ID", "rm-ras-sandbox")
	viper.SetDefault("TOPIC_ID", "topic")
	viper.SetDefault("SAMPLE_SERVICE_BASE_URL", "http://localhost:8080")
	config2 := config.Config{
		Port: viper.GetString("PORT"),
		Pubsub: config.Pubsub{
			ProjectId: viper.GetString("PROJECT_ID"),
			TopicId:   viper.GetString("TOPIC_ID"),
		},
		Sample: config.Sample{
			BaseUrl: viper.GetString("SAMPLE_SERVICE_BASE_URL"),
		},
	}
	return config2
}

func configureLogging() {
	verbose := viper.GetBool("VERBOSE")
	logrus.SetFormatter(&logrus.JSONFormatter{})
	if verbose {
		logrus.SetLevel(logrus.DebugLevel)
	} else {
		logrus.SetLevel(logrus.InfoLevel)
	}
}

func NewFileProcessor(config2 config.Config, client *pubsub.Client, ctx context.Context) file.FileProcessor {
	return file.FileProcessor{Config: config2, Client: client, Ctx: ctx}
}

func GenContext() context.Context {
	return context.Background()
}

func NewPubSub(config2 config.Config, ctx context.Context) *pubsub.Client {
	client, err := pubsub.NewClient(ctx, config2.Pubsub.ProjectId)
	if err != nil {
		logrus.WithError(err).Error("Failed to create pubsub client")
	}
	logrus.Info("Pubsub client created")
	return client
}
