env: sandbox
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "256Mi"

container:
  port: 8080
service:
  port: 8080

pubsub:
  project: rm-ras-sandbox
  topic: topic

dns:
  enabled: false
  wellKnownPort: 8080
