env: sandbox

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "25m"
    memory: "100Mi"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 250
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

gcp:
  project: rm-ras-sandbox
  topic: topic

logging:
  verbose: true

dns:
  enabled: false
  wellKnownPort: 8080
